"""
Simulates an RC circuit used to triangulate a square wave generated by a 555 timer.

Design criteria:
    - Power supply is standard 9V

    - Adjustable tempo: 1Hz -> 100Hz
    - Adjustable square/triangle blend modulation of signal: pure square -> pure triangle
    - Adjustable depth: no depth = pure signal -> full depth = amplitude modulated from muted to unattenuated
    - Footswitch toggles effect
    - Power LED indicator
    - Tempo LED flashes on beat
    - 1/4" TRS input 4V pk-pk tolerant - 10kOhm impedance
    - 1/4" TRS 800 mV RMS output - 100 Ohm impedance 

    - Triangle wave ideally is perfectly linear climb and fall from 0 V to 800 mV 
    
